# Generated by Django 3.2.14 on 2022-08-11 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=200, verbose_name='用例名称')),
                ('browser', models.CharField(choices=[('chrome', 'chrome'), ('firefox', 'firefox'), ('IE', 'IE')], max_length=200, verbose_name='浏览器')),
                ('url', models.CharField(max_length=200, verbose_name='被测网址')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '测试用例',
            },
        ),
        migrations.CreateModel(
            name='CaseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(default=1, verbose_name='测试步骤')),
                ('search_type', models.CharField(choices=[('ID', 'id'), ('XPATH', 'xpath'), ('LINK_TEXT', 'link text'), ('PARTIAL_LINK_TEXT', 'partial link text'), ('NAME', 'name'), ('TAG_NAME', 'tag name'), ('CLASS_NAME', 'class name'), ('CSS_SELECTOR', 'css selector')], max_length=200, verbose_name='定位方式')),
                ('search_value', models.CharField(max_length=200, verbose_name='定位值')),
                ('action', models.CharField(choices=[('点击', 'click'), ('输入文字', 'send_keys'), ('清楚文本', 'clear')], max_length=200, verbose_name='操作方式')),
                ('send_keys_value', models.CharField(max_length=200, verbose_name='输入内容')),
                ('testCase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoTestWeb.testcase')),
            ],
            options={
                'verbose_name_plural': 'web测试用例操作步骤',
                'ordering': ('sort',),
            },
        ),
    ]
